### ISSUE TITLE
unexpect_t doesn't appear to be used

### ISSUE THREAD

**Issue by TBBle** [ptal/std-expected-proposal#23]
Looking at [the last generated PDF](http://www.hyc.io/boost/expected-proposal.pdf) `unexpect_t` doesn't appear in the class synopsis.

It's also called `unexpet_t` in three places, and once the constant is `unexpet`.

Unless that's a different thing, and `expected` can bring your pets back from the dead, as well as all its other many C++-related uses? ^_^

**Comment by viboes** [comment]
Thanks for reporting this typo.
 
I have moved to markdown format in https://github.com/viboes/std-make/blob/master/doc/proposal/expected/DXXXXR0_expected.md

Fixed with https://github.com/viboes/std-make/commit/51183c57970c18d274361dd2062ab1b9c1b58c16

**Comment by TBBle** [comment]
It's actually still not _used_. Are we missing some constructors?
```c++
expected(unexpect_t, const E&);
expected(unexpect_t, E&&);
// This next one's in the text, but missing from the synopsis
expected(unexpected_type<E> &&);
```

**Comment by viboes** [comment]
Right. fixed any use of unexpected<E> in new repo with MarkDown format.
